# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Runs every 6 hours + allows manual run
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Generate snake SVG with dark background
      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: MrNarman
          outputs: |
            ./dist/snake.svg
          svg_background: '#0d1117'

      # Deploy to output branch
      - name: Push snake.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
